env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=tomcools/tombot
  - TAG=latest
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64

sudo: required
language: java

services:
  - docker

script:
  - docker build -t tombot -t $REPO:$TAG -f Dockerfile .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO